// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCns9zeOIfr3658ZshMeoCeIw0J76P7jew',
    appId: '1:367197686857:web:0057a96e27253f72f44398',
    messagingSenderId: '367197686857',
    projectId: 'tis-rms-9b125',
    authDomain: 'tis-rms-9b125.firebaseapp.com',
    storageBucket: 'tis-rms-9b125.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjF8X0g8zYXyZjwcTuGaIO18uNWSHDMk',
    appId: '1:367197686857:android:206f1adbe0656267f44398',
    messagingSenderId: '367197686857',
    projectId: 'tis-rms-9b125',
    storageBucket: 'tis-rms-9b125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtzcAWqG0_k1_9lZlmcwPCPKDrgfBicKI',
    appId: '1:367197686857:ios:9f3cddf3d5642563f44398',
    messagingSenderId: '367197686857',
    projectId: 'tis-rms-9b125',
    storageBucket: 'tis-rms-9b125.firebasestorage.app',
    iosClientId: '367197686857-dn38nhe5q35496touirqkno16ad70hib.apps.googleusercontent.com',
    iosBundleId: 'com.example.tisRms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtzcAWqG0_k1_9lZlmcwPCPKDrgfBicKI',
    appId: '1:367197686857:ios:9f3cddf3d5642563f44398',
    messagingSenderId: '367197686857',
    projectId: 'tis-rms-9b125',
    storageBucket: 'tis-rms-9b125.firebasestorage.app',
    iosClientId: '367197686857-dn38nhe5q35496touirqkno16ad70hib.apps.googleusercontent.com',
    iosBundleId: 'com.example.tisRms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCns9zeOIfr3658ZshMeoCeIw0J76P7jew',
    appId: '1:367197686857:web:75592cc5dc0788d5f44398',
    messagingSenderId: '367197686857',
    projectId: 'tis-rms-9b125',
    authDomain: 'tis-rms-9b125.firebaseapp.com',
    storageBucket: 'tis-rms-9b125.firebasestorage.app',
  );

}